import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { db } from "@/server/db/client"
import { GenStatus } from "@prisma/client"
import { generatePresignedGetUrl } from "@/server/services/storage"

export const dynamic = "force-dynamic"

export const metadata: Metadata = { title: "Shared Audio — YouNet Voice Studio" }

interface Props {
  params: Promise<{ token: string }>
}

export default async function SharePage({ params }: Props) {
  const { token } = await params

  const gen = await db.generation.findUnique({ where: { shareToken: token } })

  if (!gen) return notFound()
  if (gen.shareExpiresAt && gen.shareExpiresAt < new Date()) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[var(--color-surface-0)]">
        <div className="text-center space-y-2">
          <h1 className="text-display-card">Link Expired</h1>
          <p className="text-body text-[var(--color-text-secondary)]">
            This share link has expired. Please ask the owner to create a new one.
          </p>
        </div>
      </div>
    )
  }
  if (gen.status !== GenStatus.DONE) return notFound()

  const [mp3Url, wavUrl] = await Promise.all([
    gen.outputMp3Key ? generatePresignedGetUrl(gen.outputMp3Key, 3600) : null,
    gen.outputWavKey ? generatePresignedGetUrl(gen.outputWavKey, 3600) : null,
  ])

  const kindLabel = gen.kind === "PRESENTATION" ? "Presentation" : gen.kind === "PODCAST" ? "Podcast" : "Re-voiced Audio"
  const durationLabel = gen.durationMs ? `${Math.round(gen.durationMs / 1000)} seconds` : null

  return (
    <div className="min-h-screen flex items-center justify-center bg-[var(--color-surface-0)] p-6">
      <div
        className="w-full max-w-lg bg-[var(--color-surface-1)] rounded-[var(--radius-card)] p-8 space-y-6"
        style={{ boxShadow: "var(--shadow-soft-lift)" }}
      >
        <div>
          <p className="text-caption text-[var(--color-text-muted)] uppercase tracking-wider">YouNet Voice Studio</p>
          <h1 className="mt-1 text-display-card">{kindLabel}</h1>
          {durationLabel && (
            <p className="mt-1 text-body text-[var(--color-text-secondary)]">{durationLabel}</p>
          )}
        </div>

        {mp3Url && (
          <div className="space-y-2">
            <p className="text-caption text-[var(--color-text-secondary)]">Preview</p>
            <audio controls className="w-full" src={mp3Url} />
          </div>
        )}

        <div className="flex flex-col gap-3">
          {mp3Url && (
            <a
              href={mp3Url}
              download
              className="flex items-center justify-center h-10 px-6 rounded-[var(--radius-pill)] bg-black text-white text-button hover:opacity-90 transition-opacity"
            >
              Download MP3
            </a>
          )}
          {wavUrl && (
            <a
              href={wavUrl}
              download
              className="flex items-center justify-center h-10 px-6 rounded-[var(--radius-pill)] border border-[var(--color-border)] text-button hover:bg-[var(--color-surface-2)] transition-colors"
            >
              Download WAV (24-bit)
            </a>
          )}
        </div>

        <p className="text-micro text-[var(--color-text-muted)] text-center">
          Generated by YouNet Voice Studio ·{" "}
          {gen.shareExpiresAt
            ? `Link expires ${gen.shareExpiresAt.toLocaleDateString()}`
            : "No expiry"}
        </p>
      </div>
    </div>
  )
}
