ALTER TYPE "ProviderName" ADD VALUE IF NOT EXISTS 'GEMINI_LLM';
ALTER TYPE "ProviderName" ADD VALUE IF NOT EXISTS 'GROQ';
ALTER TYPE "ProviderName" ADD VALUE IF NOT EXISTS 'XAI_LLM';
ALTER TYPE "ProviderName" ADD VALUE IF NOT EXISTS 'GROK_OAUTH';
ALTER TYPE "ProviderName" ADD VALUE IF NOT EXISTS 'OLLAMA';
